<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

    <PropertyGroup>
        <RootNamespace />
        <TargetFramework>net8.0-windows</TargetFramework>
        <DefineConstants>NETCORE;NETCOREAPP30</DefineConstants>

        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AquaMate.Core\AquaMateWFC.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="BSLib">
            <HintPath>..\libs\net\BSLib.dll</HintPath>
        </Reference>
        <Reference Include="BSLib.DataViz.Model">
            <HintPath>..\libs\net\BSLib.DataViz.Model.dll</HintPath>
        </Reference>
        <Reference Include="BSLib.DataViz.WFControls">
            <HintPath>..\libs\net\BSLib.DataViz.WFControls.dll</HintPath>
        </Reference>
        <Reference Include="BSLib.Design">
            <HintPath>..\libs\net\BSLib.Design.dll</HintPath>
        </Reference>
        <Reference Include="BSLib.Design.WFHandlers">
            <HintPath>..\libs\net\BSLib.Design.WFHandlers.dll</HintPath>
        </Reference>
        <Reference Include="BSLib.Controls">
            <HintPath>..\libs\net\BSLib.Controls.dll</HintPath>
        </Reference>
        <Reference Include="RtfWriter">
            <HintPath>..\libs\net\RtfWriter.dll</HintPath>
        </Reference>
        <Reference Include="ExcelLibrary">
            <HintPath>..\libs\ExcelLibrary.dll</HintPath>
        </Reference>
        <Reference Include="ZedGraph">
            <HintPath>..\libs\ZedGraph.dll</HintPath>
        </Reference>
    </ItemGroup>


    <ItemGroup>
        <PackageReference Include="log4net" Version="3.5.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.2" />
        <PackageReference Include="NSubstitute" Version="5.0.0" />
        <PackageReference Include="NUnit" Version="3.13.3" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    </ItemGroup>

</Project>
