<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>AquaMate</RootNamespace>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <UseWindowsForms>true</UseWindowsForms>
        <DefineConstants>NETCORE;NETCOREAPP30</DefineConstants>
        <StartupObject>AquaMate.Program</StartupObject>

        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <OutputPath>..\bin</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <OutputPath>..\bin</OutputPath>
    </PropertyGroup>

    <ItemGroup>
      <Compile Include="..\AquaMate.Core\GlobalSuppressions.cs" Link="GlobalSuppressions.cs" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\AquaMate.Core\AquaMate.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="BSLib">
            <HintPath>..\libs\net\BSLib.dll</HintPath>
        </Reference>
        <Reference Include="BSLib.DataViz.Model">
            <HintPath>..\libs\net\BSLib.DataViz.Model.dll</HintPath>
        </Reference>
        <Reference Include="BSLib.DataViz.WFControls">
            <HintPath>..\libs\net\BSLib.DataViz.WFControls.dll</HintPath>
        </Reference>
        <Reference Include="BSLib.Design">
            <HintPath>..\libs\net\BSLib.Design.dll</HintPath>
        </Reference>
        <Reference Include="BSLib.Design.WFHandlers">
            <HintPath>..\libs\net\BSLib.Design.WFHandlers.dll</HintPath>
        </Reference>
        <Reference Include="BSLib.Controls">
            <HintPath>..\libs\net\BSLib.Controls.dll</HintPath>
        </Reference>
        <Reference Include="RtfWriter">
            <HintPath>..\libs\net\RtfWriter.dll</HintPath>
        </Reference>
        <Reference Include="ExcelLibrary">
            <HintPath>..\libs\ExcelLibrary.dll</HintPath>
        </Reference>
        <Reference Include="ZedGraph">
            <HintPath>..\libs\ZedGraph.dll</HintPath>
        </Reference>
        <Reference Include="ZLMKit">
            <HintPath>..\libs\net\ZLMKit.dll</HintPath>
        </Reference>
    </ItemGroup>


    <ItemGroup>
        <PackageReference Include="log4net" Version="3.5.0" />
        <PackageReference Include="OpenTK.GLControl" Version="4.0.2" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\btn_accept.gif" />
        <EmbeddedResource Include="Resources\btn_cancel.gif" />
        <EmbeddedResource Include="Resources\btn_exit.gif" />
        <EmbeddedResource Include="Resources\btn_left.gif" />
        <EmbeddedResource Include="Resources\btn_right.gif" />
        <EmbeddedResource Include="Resources\btn_rec_delete.gif" />
        <EmbeddedResource Include="Resources\btn_rec_edit.gif" />
        <EmbeddedResource Include="Resources\btn_rec_new.gif" />
        <EmbeddedResource Include="Resources\btn_excel.gif" />
        <EmbeddedResource Include="Resources\btn_chart.gif" />
        <EmbeddedResource Include="Resources\icon_aquamate.ico" />
        <EmbeddedResource Include="Resources\btn_help.gif" />
        <EmbeddedResource Include="Resources\btn_tools.gif" />
    </ItemGroup>
</Project>
